# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LatlongcalculatorDialog
                                 A QGIS plugin
 Latitude Longitude calculator
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-22
        git sha              : $Format:%H$
        copyright            : (C) 2021 by chikubanda
        email                : chikubanda@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'latlongcalculator_dialog_base.ui'))


class LatlongcalculatorDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(LatlongcalculatorDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        #connect function to degree input that will be called on each change
        self.latDegreeSpinBox.valueChanged.connect(self.latDMStoDD)

    def latDMStoDD():
        iDeg = self.latDegreeSpinBox.value()

        dDD = float(iDeg)

        self.spdLatDD.setValue(dDD)
